package com.zhipu.oapi.service.v4.assistant.message.tools.drawing_tool;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
     * The input string that was used to generate the drawing.
     */
public class DrawingTool {

    /**
     * The input string that was used to generate the drawing.
     */
    @JsonProperty("input")
    private String input;

    /**
     * A list of outputs generated by the drawing tool.
     */
    @JsonProperty("outputs")
    private List<DrawingToolOutput> outputs;

    // Getters and Setters

    public String getInput() {
        return input;
    }

    public void setInput(String input) {
        this.input = input;
    }

    public List<DrawingToolOutput> getOutputs() {
        return outputs;
    }

    public void setOutputs(List<DrawingToolOutput> outputs) {
        this.outputs = outputs;
    }
}
